/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-bright": "#363940",
              "primary-container": "#23a382",
              "surface-container-highest": "#32353c",
              "secondary-fixed-dim": "#72d2fd",
              "tertiary-fixed": "#a7f786",
              "surface": "#10131a",
              "surface-dim": "#10131a",
              "on-surface": "#e1e2eb",
              "surface-container": "#1d2026",
              "on-primary-container": "#003024",
              "surface-tint": "#67dab6",
              "on-tertiary-fixed-variant": "#155200",
              "surface-base": "#131722",
              "accent-green": "#549E39",
              "on-secondary-fixed-variant": "#004d65",
              "secondary": "#72d2fd",
              "on-secondary-container": "#002e3e",
              "on-tertiary-fixed": "#052100",
              "accent-blue": "#0989B1",
              "surface-container-low": "#191c22",
              "on-surface-variant": "#bccac2",
              "surface-container-high": "#272a31",
              "error": "#ffb4ab",
              "tertiary-fixed-dim": "#8cda6d",
              "on-error-container": "#ffdad6",
              "background": "#10131a",
              "outline-variant": "#3d4944",
              "error-container": "#93000a",
              "on-background": "#e1e2eb",
              "on-primary-fixed": "#002117",
              "surface-deep": "#0B0E14",
              "accent-teal": "#029676",
              "on-secondary-fixed": "#001f2a",
              "secondary-fixed": "#bfe9ff",
              "surface-variant": "#32353c",
              "secondary-container": "#309bc4",
              "on-secondary": "#003547",
              "on-primary": "#00382a",
              "primary-fixed-dim": "#67dab6",
              "inverse-on-surface": "#2e3037",
              "tertiary": "#8cda6d",
              "warning-orange": "#FB8C00",
              "glass-fill": "rgba(19, 23, 34, 0.6)",
              "primary-fixed": "#85f7d2",
              "outline": "#87948d",
              "on-tertiary": "#0c3900",
              "on-tertiary-container": "#093100",
              "on-error": "#690005",
              "inverse-surface": "#e1e2eb",
              "surface-container-lowest": "#0b0e14",
              "tertiary-container": "#58a23c",
              "inverse-primary": "#006b54",
              "on-primary-fixed-variant": "#00513e",
              "error-red": "#E53935",
              "primary": "#67dab6"
          },
          borderRadius: {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          spacing: {
              "gutter-desktop": "24px",
              "max-width": "1440px",
              "margin-desktop": "40px",
              "gutter-mobile": "16px",
              "unit": "4px",
              "margin-mobile": "20px"
          },
          fontFamily: {
              "label-md": ["Inter"],
              "headline-lg": ["Inter"],
              "headline-md": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "label-lg": ["Inter"],
              "body-lg": ["Inter"],
              "headline-xl": ["Inter"],
              "body-sm": ["Inter"],
              "body-md": ["Inter"]
          },
          fontSize: {
              "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
              "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
              "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
          }
      }
  },
  plugins: [],
}
